<template>
  <div>
    <h2>TEST LINELIST JSPDF</h2>
    <button @click="generatePDF">Generate PDF</button>
    <pre>{{ tableData }}</pre>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from "vue";
import jsPDF from "jspdf";
import "jspdf-autotable";

export default defineComponent({
  setup() {
    const tableData = ref([
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
      {
        no: 1,
        accessionNo: "ACC001",
        name: "Sample 1",
        biologicalMaterial: "Tissue",
        storedBy: "John Doe",
        remarks: "First sample",
      },
      {
        no: 2,
        accessionNo: "ACC002",
        name: "Sample 2",
        biologicalMaterial: "Blood",
        storedBy: "Jane Doe",
        remarks: "Second sample",
      },
      {
        no: 3,
        accessionNo: "ACC003",
        name: "Sample 3",
        biologicalMaterial: "Cells",
        storedBy: "Bob Smith",
        remarks: "Third sample",
      },
      {
        no: 4,
        accessionNo: "ACC004",
        name: "Sample 4",
        biologicalMaterial: "DNA",
        storedBy: "Alice Johnson",
        remarks: "Fourth sample",
      },
      {
        no: 5,
        accessionNo: "ACC005",
        name: "Sample 5",
        biologicalMaterial: "Tissue",
        storedBy: "Eve Brown",
        remarks: "Fifth sample",
      },
      {
        no: 6,
        accessionNo: "ACC006",
        name: "Sample 6",
        biologicalMaterial: "Blood",
        storedBy: "Charlie White",
        remarks: "Sixth sample",
      },
      {
        no: 7,
        accessionNo: "ACC007",
        name: "Sample 7",
        biologicalMaterial: "Cells",
        storedBy: "David Black",
        remarks: "Seventh sample",
      },
      {
        no: 8,
        accessionNo: "ACC008",
        name: "Sample 8",
        biologicalMaterial: "DNA",
        storedBy: "Frank Red",
        remarks: "Eighth sample",
      },
      {
        no: 9,
        accessionNo: "ACC009",
        name: "Sample 9",
        biologicalMaterial: "Tissue",
        storedBy: "Grace Green",
        remarks: "Ninth sample",
      },
      {
        no: 10,
        accessionNo: "ACC010",
        name: "Sample 10",
        biologicalMaterial: "Blood",
        storedBy: "Harry Blue",
        remarks: "Tenth sample",
      },
      // ... Repeat similar structures for 90 more items
      {
        no: 100,
        accessionNo: "ACC100",
        name: "Sample 100",
        biologicalMaterial: "Cells",
        storedBy: "Alice Smith",
        remarks: "One hundredth sample",
      },
    ]);

    const generatePDF = () => {
      const doc = new jsPDF();

      const tableColumn = [
        "no",
        "accessionNo",
        "name",
        "biologicalMaterial",
        "storedBy",
        "remarks",
      ];
      let tableRows = []; // Change from const to let

      // Add table rows
      tableData.value.forEach((dataRow) => {
        const rowData = Object.values(dataRow);
        tableRows.push(rowData);
      });

      // Function to add page count to the footer
      const addPageCount = () => {
        const pageCount = doc.internal.getNumberOfPages();
        doc.setFontSize(12);
        doc.text(
          `Page ${pageCount} of ${pageCount}`,
          doc.internal.pageSize.width - 10,
          doc.internal.pageSize.height - 10,
          { align: "right" }
        );
      };

      // Set up a page event to add the page count to the footer on each page
      doc.autoTable({
        head: [tableColumn],
        body: tableRows,
        didDrawPage: () => addPageCount(),
      });

      // Add logos and other content to the header
      const logoWidth = 30;
      const logoHeight = 30;
      const leftLogoX = 10;
      const rightLogoX = doc.internal.pageSize.width - logoWidth - 10;

      //   doc.addImage(
      //     "path/to/left-logo.png",
      //     "PNG",
      //     leftLogoX,
      //     10,
      //     logoWidth,
      //     logoHeight
      //   );
      //   doc.addImage(
      //     "path/to/right-logo.png",
      //     "PNG",
      //     rightLogoX,
      //     10,
      //     logoWidth,
      //     logoHeight
      //   );

      // Save the PDF with a specific name
      doc.save("table.pdf");
    };

    onMounted(async () => {
      //   try {
      //     const response = await fetch("/json/test.json"); // Adjust the path accordingly
      //     if (response.ok) {
      //       tableData.value = await response.json();
      //     } else {
      //       console.error("Failed to fetch test data");
      //     }
      //   } catch (error) {
      //     console.error("Error fetching test data:", error);
      //   }
    });

    return {
      generatePDF,
      tableData,
    };
  },
});
</script>

<style scoped></style>
